import { format } from 'date-fns';

interface ReportData {
  title: string;
  subtitle?: string;
  dateRange?: { from: string; to: string };
  tenant?: {
    name: string;
    company_name?: string | null;
    logo_url?: string | null;
    phone?: string | null;
    address?: string | null;
  };
  summary?: Array<{ label: string; value: string | number; type?: 'positive' | 'negative' | 'neutral' }>;
  columns: string[];
  rows: Array<(string | number)[]>;
  footer?: string;
}

export function generateReportHTML(data: ReportData): string {
  const summaryHTML = data.summary ? `
    <div class="summary">
      ${data.summary.map(item => `
        <div class="summary-card ${item.type || 'neutral'}">
          <div class="summary-label">${item.label}</div>
          <div class="summary-value">${typeof item.value === 'number' ? `৳${item.value.toLocaleString()}` : item.value}</div>
        </div>
      `).join('')}
    </div>
  ` : '';

  const tableHeaders = data.columns.map(col => `<th>${col}</th>`).join('');
  const tableRows = data.rows.map(row => 
    `<tr>${row.map((cell, idx) => 
      `<td class="${idx === row.length - 1 ? 'text-right' : ''}">${cell}</td>`
    ).join('')}</tr>`
  ).join('');

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <title>${data.title}</title>
      <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: Arial, sans-serif; font-size: 12px; padding: 30px; color: #333; }
        
        .header { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 2px solid #333; padding-bottom: 15px; margin-bottom: 20px; }
        .logo img { max-width: 80px; max-height: 40px; }
        .company { margin-top: 5px; }
        .company-name { font-size: 18px; font-weight: bold; }
        .company-info { font-size: 10px; color: #666; }
        
        .title-section { text-align: right; }
        .title { font-size: 20px; font-weight: bold; text-transform: uppercase; }
        .date-range { font-size: 11px; color: #666; margin-top: 5px; }
        
        .summary { display: flex; gap: 15px; margin-bottom: 25px; flex-wrap: wrap; }
        .summary-card { flex: 1; min-width: 150px; padding: 15px; border-radius: 8px; background: #f8f9fa; }
        .summary-card.positive { background: #d4edda; }
        .summary-card.negative { background: #f8d7da; }
        .summary-label { font-size: 10px; color: #666; text-transform: uppercase; letter-spacing: 0.5px; }
        .summary-value { font-size: 18px; font-weight: bold; margin-top: 5px; }
        .summary-card.positive .summary-value { color: #155724; }
        .summary-card.negative .summary-value { color: #721c24; }
        
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        th { background: #f0f0f0; padding: 10px 8px; text-align: left; font-weight: 600; border-bottom: 2px solid #ddd; font-size: 11px; }
        td { padding: 8px; border-bottom: 1px solid #eee; font-size: 11px; }
        tr:nth-child(even) { background: #fafafa; }
        .text-right { text-align: right; }
        
        .footer { margin-top: 30px; padding-top: 15px; border-top: 1px solid #ddd; text-align: center; font-size: 10px; color: #666; }
        
        @media print {
          body { padding: 15px; }
          .no-print { display: none; }
        }
      </style>
    </head>
    <body>
      <div class="header">
        <div>
          ${data.tenant?.logo_url ? `<div class="logo"><img src="${data.tenant.logo_url}" alt="Logo" /></div>` : ''}
          <div class="company">
            <div class="company-name">${data.tenant?.company_name || data.tenant?.name || 'Company'}</div>
            <div class="company-info">
              ${data.tenant?.address || ''}<br/>
              ${data.tenant?.phone ? `Tel: ${data.tenant.phone}` : ''}
            </div>
          </div>
        </div>
        <div class="title-section">
          <div class="title">${data.title}</div>
          ${data.subtitle ? `<div class="date-range">${data.subtitle}</div>` : ''}
          ${data.dateRange ? `<div class="date-range">${data.dateRange.from} to ${data.dateRange.to}</div>` : ''}
          <div class="date-range">Generated: ${format(new Date(), 'dd MMM yyyy HH:mm')}</div>
        </div>
      </div>

      ${summaryHTML}

      <table>
        <thead>
          <tr>${tableHeaders}</tr>
        </thead>
        <tbody>
          ${tableRows}
        </tbody>
      </table>

      <div class="footer">
        ${data.footer || 'Report generated by ISP Manager'}
      </div>
    </body>
    </html>
  `;
}

export function printReport(data: ReportData): void {
  const html = generateReportHTML(data);
  const printWindow = window.open('', '_blank');
  if (!printWindow) return;
  
  printWindow.document.write(html);
  printWindow.document.close();
  printWindow.onload = () => {
    printWindow.print();
  };
}

// Helper functions for specific reports
export function generateDuesReport(
  customers: Array<{ code: string; name: string; phone: string; due: number }>,
  tenant?: ReportData['tenant']
): ReportData {
  const totalDue = customers.reduce((sum, c) => sum + c.due, 0);
  
  return {
    title: 'Customer Dues Report',
    subtitle: `${customers.length} customers with outstanding balance`,
    tenant,
    summary: [
      { label: 'Total Customers', value: customers.length, type: 'neutral' },
      { label: 'Total Due Amount', value: totalDue, type: 'negative' },
      { label: 'Average Due', value: customers.length > 0 ? Math.round(totalDue / customers.length) : 0, type: 'neutral' },
    ],
    columns: ['#', 'Customer Code', 'Customer Name', 'Phone', 'Due Amount'],
    rows: customers.map((c, idx) => [
      idx + 1,
      c.code,
      c.name,
      c.phone || '-',
      `৳${c.due.toLocaleString()}`
    ]),
  };
}

export function generateCustomerListReport(
  customers: Array<{ code: string; name: string; phone: string; company: string; total: number; due: number }>,
  tenant?: ReportData['tenant']
): ReportData {
  return {
    title: 'Customer List',
    subtitle: `Total ${customers.length} customers`,
    tenant,
    columns: ['#', 'Code', 'Name', 'Phone', 'Company', 'Total Purchase', 'Due'],
    rows: customers.map((c, idx) => [
      idx + 1,
      c.code,
      c.name,
      c.phone || '-',
      c.company || '-',
      `৳${c.total.toLocaleString()}`,
      `৳${c.due.toLocaleString()}`
    ]),
  };
}

export function generateSalesReport(
  sales: Array<{ invoice: string; date: string; customer: string; total: number; paid: number; due: number }>,
  dateRange: { from: string; to: string },
  tenant?: ReportData['tenant']
): ReportData {
  const totalSales = sales.reduce((sum, s) => sum + s.total, 0);
  const totalPaid = sales.reduce((sum, s) => sum + s.paid, 0);
  const totalDue = sales.reduce((sum, s) => sum + s.due, 0);

  return {
    title: 'Sales Report',
    dateRange,
    tenant,
    summary: [
      { label: 'Total Invoices', value: sales.length, type: 'neutral' },
      { label: 'Total Sales', value: totalSales, type: 'positive' },
      { label: 'Amount Collected', value: totalPaid, type: 'positive' },
      { label: 'Outstanding', value: totalDue, type: 'negative' },
    ],
    columns: ['#', 'Invoice', 'Date', 'Customer', 'Total', 'Paid', 'Due'],
    rows: sales.map((s, idx) => [
      idx + 1,
      s.invoice,
      s.date,
      s.customer,
      `৳${s.total.toLocaleString()}`,
      `৳${s.paid.toLocaleString()}`,
      `৳${s.due.toLocaleString()}`
    ]),
  };
}

export function generateInventoryReport(
  items: Array<{ sku: string; name: string; category: string; qty: number; price: number; value: number }>,
  tenant?: ReportData['tenant']
): ReportData {
  const totalValue = items.reduce((sum, i) => sum + i.value, 0);
  const lowStock = items.filter(i => i.qty <= 5).length;

  return {
    title: 'Inventory Report',
    subtitle: `${items.length} products in stock`,
    tenant,
    summary: [
      { label: 'Total Products', value: items.length, type: 'neutral' },
      { label: 'Total Stock Value', value: totalValue, type: 'positive' },
      { label: 'Low Stock Items', value: lowStock, type: lowStock > 0 ? 'negative' : 'neutral' },
    ],
    columns: ['#', 'SKU', 'Product Name', 'Category', 'Qty', 'Unit Price', 'Stock Value'],
    rows: items.map((i, idx) => [
      idx + 1,
      i.sku || '-',
      i.name,
      i.category || '-',
      i.qty,
      `৳${i.price.toLocaleString()}`,
      `৳${i.value.toLocaleString()}`
    ]),
  };
}

export function generateSupplierDuesReport(
  suppliers: Array<{ name: string; company: string; phone: string; due: number }>,
  tenant?: ReportData['tenant']
): ReportData {
  const totalDue = suppliers.reduce((sum, s) => sum + s.due, 0);

  return {
    title: 'Supplier Dues Report',
    subtitle: `${suppliers.length} suppliers with outstanding payments`,
    tenant,
    summary: [
      { label: 'Total Suppliers', value: suppliers.length, type: 'neutral' },
      { label: 'Total Due Amount', value: totalDue, type: 'negative' },
    ],
    columns: ['#', 'Supplier Name', 'Company', 'Phone', 'Due Amount'],
    rows: suppliers.map((s, idx) => [
      idx + 1,
      s.name,
      s.company || '-',
      s.phone || '-',
      `৳${s.due.toLocaleString()}`
    ]),
  };
}
